'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { beginLocalLogin, loadMemberProfilePhoto, loadOrganizationMember, restoreLocalLogin, uploadMemberProfilePhoto, type OrganizationMemberDetail, type Viewer } from '../local-auth';

export function OrganizationMemberWorkspace({ userId }: { userId: string }) {
  const [member, setMember] = useState<OrganizationMemberDetail>();
  const [message, setMessage] = useState<string>();
  const [signInRequired, setSignInRequired] = useState(false);
  const [viewer, setViewer] = useState<Viewer>();
  const [profilePhotoUrl, setProfilePhotoUrl] = useState<string | null>();
  const [uploading, setUploading] = useState(false);
  useEffect(() => { void (async () => { try { const currentViewer = await restoreLocalLogin(); if (!currentViewer) { setSignInRequired(true); return; } setViewer(currentViewer); const [nextMember, photo] = await Promise.all([loadOrganizationMember(userId), loadMemberProfilePhoto(userId)]); setMember(nextMember); setProfilePhotoUrl(photo.profilePhotoUrl); } catch (error) { setMessage(error instanceof Error ? error.message : 'Organization member could not be loaded.'); } })(); }, [userId]);
  const canEditPhoto = viewer?.userId === userId || viewer?.roles.some((role) => ['organization_admin', 'principal', 'project_manager'].includes(role));
  const onPhotoSelected = async (file: File | undefined) => { if (!file) return; setUploading(true); setMessage(undefined); try { const result = await uploadMemberProfilePhoto(userId, file); setProfilePhotoUrl(result.profilePhotoUrl); } catch (error) { setMessage(error instanceof Error ? error.message : 'Profile photo could not be uploaded.'); } finally { setUploading(false); } };
  if (signInRequired) return <main className="record-page"><section className="content-card record-page-card auth-required"><p className="eyebrow">ORGANIZATION DIRECTORY</p><h1>Sign in to view this member</h1><button className="button-primary" onClick={() => void beginLocalLogin()}>Sign in</button></section></main>;
  if (!member) return <main className="record-page"><p className="settings-empty">{message ?? 'Loading organization member…'}</p></main>;
  return <main className="record-page" aria-label={`Organization member ${member.display_name}`}><header className="record-page-header"><div><Link href="/" className="back-link">← Back to workspace</Link><p className="eyebrow">ORGANIZATION MEMBER</p><h1>{member.display_name}</h1><p>{member.title ?? 'No job title'} · {member.organization_role ?? 'project member'}</p></div><span className="status-pill current">{member.active ? 'active' : 'inactive'}</span></header><section className="content-card record-page-card"><div className="member-profile-photo">{profilePhotoUrl ? <img src={profilePhotoUrl} alt={`${member.display_name} profile`} /> : <span>{member.display_name.slice(0, 2).toUpperCase()}</span>}<div><h2>Profile photo</h2><p>JPEG, PNG, or WebP · maximum 5 MB.</p>{canEditPhoto && <label className="button-secondary">{uploading ? 'Uploading…' : 'Upload profile photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void onPhotoSelected(event.target.files?.[0])} disabled={uploading} hidden /></label>}</div></div>{message && <p className="form-message">{message}</p>}</section><section className="content-card record-page-card"><div className="record-grid"><div><span>Member ID</span><strong>{member.member_id}</strong></div><div><span>Weekly capacity</span><strong>{member.weekly_capacity_hours}h</strong></div><div><span>Organization role</span><strong>{(member.organization_role ?? 'project_member').replaceAll('_', ' ')}</strong></div></div></section><section className="content-card record-page-card"><div className="card-header"><div><p className="eyebrow">PROJECT ASSIGNMENTS</p><h2>Delivery teams</h2></div><span>{member.projects.length}</span></div>{member.projects.length ? <div className="simple-record-list">{member.projects.map((project) => <article key={project.id}><strong>{project.code} · {project.name}</strong><span>{project.role.replaceAll('_', ' ')}</span></article>)}</div> : <p className="settings-empty">This organization member has not been assigned to a project.</p>}</section></main>;
}
